### ISSUE TITLE
Issues blocking publication

### ISSUE THREAD

**Issue by davelab6** [mjlagattuta/Hepta-Slab#11]
- [ ] the GF eng team couldn't push because of OTS failure, and 

- [ ] the OS/2 weight class 200 doesn't match with the given weight 400 in METADATA.pb, and isn't a weight < 250.

**Comment by m4rc1e** [comment]
Font passes latest ots.

```
Marcs-Air:Type marcfoley$ ./ots-sanitize /Users/marcfoley/Type/fonts/ofl/heptaslab/HeptaSlab\[wght\].ttf 
File sanitized successfully!
```

I'll look at the weight class now.

**Comment by m4rc1e** [comment]
weight in METADATA.pb file fixed, https://github.com/google/fonts/pull/2099. It should now work. If Nathan can push the pr, we should close this issue.

**Comment by davelab6** [comment]
Thank you Marc, sorry for the false alarm :)
